### ISSUE TITLE
Quark Cabinets Issue

### ISSUE THREAD

**Issue by Jkosio23** [mrh0/buildersaddition#22]
Here's the error that was coming up in the console when I got it. Looks like something to do with your quark compatibility.
Minecraft: 1.16.5
Forge: 36.0.1
Quark: r2.4-298
Builders Addition: 1.16.4-20210124a

https://paste.gg/p/anonymous/04dc6f9da22545fcb8086b8e31eac931/files/ecccdf21044549dca2c05e69a34fa6db/raw

**Comment by mrh0** [comment]
This was fixed in 20210127a

**Comment by Dum4G** [comment]
Somehow is happening again on 20210214a

**Comment by Dum4G** [comment]
One thing left to fix on 1.16.4-20210224a @mrh0 

`        at java.util.Optional.orElseThrow(Unknown Source) ~[?:?] {}
        at net.minecraft.item.crafting.Ingredient.func_199803_a(IngredientMixin.java:215) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:item.crafting.IngredientMixin,pl:mixin:A}
        at net.minecraftforge.common.crafting.VanillaIngredientSerializer.parse(VanillaIngredientSerializer.java:41) ~[forge:?] {re:classloading}
        at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:155) ~[forge:?] {re:mixin,re:classloading}
        at net.minecraft.item.crafting.Ingredient.func_199802_a(IngredientMixin.java:189) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:item.crafting.IngredientMixin,pl:mixin:A}
        at net.minecraft.item.crafting.ShapedRecipe.func_192408_a(ShapedRecipeMixin.java:252) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:item.crafting.ShapedRecipeMixin,pl:mixin:A}
        at net.minecraft.item.crafting.ShapedRecipe.access$000(ShapedRecipeMixin.java:24) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:item.crafting.ShapedRecipeMixin,pl:mixin:A}
        at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:276) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:272) ~[?:?] {re:classloading}
        at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManagerMixin.java:141) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:item.crafting.RecipeManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManagerMixin.java:568) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:item.crafting.RecipeManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManagerMixin.java:38) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:item.crafting.RecipeManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] {}
        at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
        at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] {}
        at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
        at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] {}
        at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
        at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?] {}
        at net.minecraft.resources.AsyncReloader$1.func_216873_a(SourceFile:53) ~[?:?] {re:classloading}
        at net.minecraft.resources.AsyncReloader$1.func_216872_a(SourceFile:50) ~[?:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) [?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?] {}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?] {}
[15:49:03] [Worker-Main-4/INFO] [minecraft/RecipeManager]: Skipping loading recipe woodcutter:oak_seat_from_oak_planks as it's conditions were not met
[15:49:03] [Worker-Main-4/INFO] [minecraft/RecipeManager]: Skipping loading recipe corail_woodcutter:woodcutting/spruce_support_from_spruce_planks as it's conditions were not met
[15:49:03] [Worker-Main-4/INFO] [minecraft/RecipeManager]: Skipping loading recipe corail_woodcutter:woodcutting/acacia_palisade_from_acacia_logs as it's conditions were not met
[15:49:03] [Worker-Main-4/INFO] [minecraft/RecipeManager]: Skipping loading recipe woodcutter:mahogany_seat_from_mahogany_planks as it's conditions were not met`

**Comment by mrh0** [comment]
Fixed, will be in the next update.
