### ISSUE TITLE
Vertical slab crashed with create's mechanical_bearing

### ISSUE THREAD

**Issue by Sam-Chai** [mrh0/buildersaddition#29]
When I build a structure like this:
![image](https://user-images.githubusercontent.com/29940426/114209502-44e38080-9991-11eb-89a8-d91fb2f87f47.png)
then I left-click create's mechanical_bearing to start rotate, and its crashed ;<
**Create version: create-mc1.16.5_v0.3.1a**
**Builder-addition version: buildersaddition-1.16.5-20210407a**

**The crash report:**
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2021/4/10 上午12:12
Description: Unexpected error

java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.client.renderer.WorldRenderer.func_228423_a_(WorldRenderer.java:2113) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.bbor.json:client.renderer.MixinGameRenderer,pl:mixin:APP:supplementaries.mixins.json:ParrotPartyMixin,pl:mixin:APP:betterendforge.mixins.json:WorldRendererMixin,pl:mixin:APP:create.mixins.json:RenderHooksMixin,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1750) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.bbor.json:client.renderer.MixinGameRenderer,pl:mixin:APP:supplementaries.mixins.json:ParrotPartyMixin,pl:mixin:APP:betterendforge.mixins.json:WorldRendererMixin,pl:mixin:APP:create.mixins.json:RenderHooksMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:fairylights:GameRendererTransformer,pl:mixin:APP:mixins.modernui-forge.json:AccessGameRenderer,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:fairylights:GameRendererTransformer,pl:mixin:APP:mixins.modernui-forge.json:AccessGameRenderer,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.bbor.json:client.MixinMinecraft,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.lightfall.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.bbor.json:client.MixinMinecraft,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.lightfall.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[AtlantisPowered.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.4.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.WorldRenderer.func_228423_a_(WorldRenderer.java:2113) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.bbor.json:client.renderer.MixinGameRenderer,pl:mixin:APP:supplementaries.mixins.json:ParrotPartyMixin,pl:mixin:APP:betterendforge.mixins.json:WorldRendererMixin,pl:mixin:APP:create.mixins.json:RenderHooksMixin,pl:mixin:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1750) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.bbor.json:client.renderer.MixinGameRenderer,pl:mixin:APP:supplementaries.mixins.json:ParrotPartyMixin,pl:mixin:APP:betterendforge.mixins.json:WorldRendererMixin,pl:mixin:APP:create.mixins.json:RenderHooksMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:fairylights:GameRendererTransformer,pl:mixin:APP:mixins.modernui-forge.json:AccessGameRenderer,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Sam_Chai'/3, l='ClientLevel', x=148.07, y=6.12, z=196.83]]
	Chunk stats: Client Chunk Cache: 625, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (144,4,192), Chunk: (at 0,0,0 in 9,12; contains blocks 144,0,192 to 159,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3325 game time, 3325 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.bbor.json:client.world.MixinClientWorld,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.bbor.json:client.MixinMinecraft,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.lightfall.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.bbor.json:client.MixinMinecraft,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.lightfall.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[AtlantisPowered.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.4.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 11.0.10, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 2403138000 bytes (2291 MB) / 3925868544 bytes (3744 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/%5BVisual%5DOptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.4.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.4
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		[Fix]torchslabmod-1.16.4_v1.6.18.jar              |Torch Slab Mod                |torchslabmod                  |1.6.18              |DONE      |NOSIGNATURE
		[Extra]BBOutlineReloaded-2.4-1.16.3-forge.jar     |BoundingBoxOutlineReloaded    |bbor                          |2.4-1.16.3          |DONE      |NOSIGNATURE
		[Lib]jei-1.16.5-7.6.1.75.jar                      |Just Enough Items             |jei                           |7.6.1.75            |DONE      |NOSIGNATURE
		[Lib]jei-professions-1.0.0-1.16.4.jar             |JEI Professions               |jeiprofessions                |1.0.0               |DONE      |NOSIGNATURE
		[Lib][extra_boat&famers_delight]abnormals_core-1.1|Abnormals Core                |abnormals_core                |3.1.1               |DONE      |NOSIGNATURE
		[M]goblintraders-1.2.2-1.16.3.jar                 |Goblin Traders                |goblintraders                 |1.2.2               |DONE      |NOSIGNATURE
		[M]Mekanism-1.16.5-10.0.21.448.jar                |Mekanism                      |mekanism                      |10.0.21             |DONE      |NOSIGNATURE
		[M]extraboats-1.16.5-2.1.0.jar                    |Extra Boats                   |extraboats                    |2.1.0               |DONE      |NOSIGNATURE
		[Extra]findme-1.16.3-2.1.0.0.jar                  |Find Me                       |findme                        |NONE                |DONE      |NOSIGNATURE
		[M]create-mc1.16.5_v0.3.1a.jar                    |Create                        |create                        |mc1.16.5_v0.3.1a+128|DONE      |NOSIGNATURE
		[M]mightyarchitect-mc1.16.3_v0.5.jar              |The Mighty Architect          |mightyarchitect               |0.5                 |DONE      |NOSIGNATURE
		[FTB]ftb-gui-library-1604.1.1.26.jar              |FTB GUI Library               |ftbguilibrary                 |1604.1.1.26         |DONE      |NOSIGNATURE
		[Lib]Bookshelf-1.16.5-10.0.7.jar                  |Bookshelf                     |bookshelf                     |10.0.7              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		[Visual]Tips-1.16.5-4.0.7.jar                     |Tips                          |tips                          |4.0.7               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		[Visual]WAWLA-1.16.5-8.0.1.jar                    |WAWLA                         |wawla                         |8.0.1               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		[Fix]randompatches-2.4.4-forge.jar                |RandomPatches                 |randompatches                 |2.4.4-forge         |DONE      |92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		[Tool]JEITweaker-1.16.5-1.0.1.14.jar              |JEI Tweaker                   |jeitweaker                    |1.0.1.14            |DONE      |NOSIGNATURE
		[M]carpetstairsmod-1.16.4_v1.4.7.jar              |Carpet Stairs Mod             |carpetstairsmod               |1.4.7               |DONE      |NOSIGNATURE
		[Visual]chat_heads_forge-0.2.0.jar                |Chat Heads                    |chat_heads                    |0.2.0               |DONE      |NOSIGNATURE
		[Tool]CraftTweaker-1.16.5-7.1.0.194.jar           |CraftTweaker                  |crafttweaker                  |7.1.0.194           |DONE      |NOSIGNATURE
		[Lib]JustEnoughResources-1.16.3-0.12.0.100 (1).jar|Just Enough Resources         |jeresources                   |0.12.0.100          |DONE      |NOSIGNATURE
		[FTB]ftb-chunks-1604.2.2.54.jar                   |FTB Chunks                    |ftbchunks                     |1604.2.2.54         |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.4-universal.jar                 |Forge                         |forge                         |36.1.4              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		[Extra]stackrefill_1.16.5-1.7.jar                 |Stack Refill                  |stackrefill                   |1.7                 |DONE      |NOSIGNATURE
		[M]RevampedWolf-1.16.4-0.7.1.jar                  |RevampedWolf                  |revampedwolf                  |1.16.4-0.7.1        |DONE      |NOSIGNATURE
		[M]supplementaries-1.16.5-0.11.0b.jar             |Supplementaries               |supplementaries               |1.16.5-0.11.0       |DONE      |NOSIGNATURE
		[M]betterendforge-1.16.4-1.5.1.jar                |BetterEnd Forge               |betterendforge                |1.16.4-1.5.1        |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.4-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		[M]FarmersDelight-1.16.3-0.4.0.jar                |Farmer's Delight              |farmersdelight                |1.16.3-0.4.0        |DONE      |NOSIGNATURE
		[Service]voicechat-1.16.5-1.1.5.jar               |Simple Voice Chat             |voicechat                     |1.16.5-1.1.5        |DONE      |NOSIGNATURE
		[Visual]theoneprobe-1.16-3.0.7.jar                |The One Probe                 |theoneprobe                   |1.16-3.0.7          |DONE      |NOSIGNATURE
		[Extra]MouseTweaks-2.13-mc1.16.2.jar              |Mouse Tweaks                  |mousetweaks                   |2.13                |DONE      |NOSIGNATURE
		[Service]AllMusic-2.3.0(hotfix).jar               |AllMusic                      |allmusic                      |2.3.0               |DONE      |NOSIGNATURE
		[Lib]smoothboot-forge-1.16.4-1.2.2.jar            |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |NOSIGNATURE
		[Tool]CreateTweaker-1.0.0.9.jar                   |CreateTweaker                 |createtweaker                 |1.0.0.9             |DONE      |NOSIGNATURE
		[M]fairylights-4.0.4-1.16.4.jar                   |Fairy Lights                  |fairylights                   |4.0.4               |DONE      |NOSIGNATURE
		[M]Coals_Crafting-1.16.5-1.3.2.jar                |Coals Crafting                |coals_crafting                |1.3.2               |DONE      |NOSIGNATURE
		[Visual]ShulkerTooltip-1.9.7.jar                  |Shulker Tooltip               |shulkertooltip                |1.9.7               |DONE      |NOSIGNATURE
		[M]Croptopia-1.16.4-FORGE-1.1.0.jar               |Croptopia                     |croptopia                     |NONE                |DONE      |NOSIGNATURE
		[Lib]collective-1.16.5-2.25.jar                   |Collective                    |collective                    |2.25                |DONE      |NOSIGNATURE
		[Visual]topaddons-1.16.5-2.1.1-beta.jar           |TOP Addons                    |topaddons                     |1.16.5-2.1.1-beta   |DONE      |NOSIGNATURE
		[M]FluxNetworks-1.16.5-6.1.6.11.jar               |Flux Networks                 |fluxnetworks                  |1.16.5-6.1.6.11     |DONE      |NOSIGNATURE
		[Lib]JustEnoughCharacters-1.16.4-4.1.5.jar        |Just Enough Characters        |jecharacters                  |4.1.5               |DONE      |NOSIGNATURE
		[Extra]ftb-ultimine-1605.2.0-build.26-forge.jar   |FTB Ultimine                  |ftbultimine                   |1605.2.0-build.26   |DONE      |NOSIGNATURE
		[M]buildersaddition-1.16.5-20210407a.jar          |Builders Crafts & Addition    |buildersaddition              |1.16.5-20210407a    |DONE      |NOSIGNATURE
		[Visual]WorldEdit-CUI-FE3-1.16.4-3.0.8.jar        |WorldEdit CUI Forge Edition 3 |worldeditcuife3               |3.0.8               |DONE      |NOSIGNATURE
		[M]MekanismTools-1.16.5-10.0.21.448.jar           |Mekanism: Tools               |mekanismtools                 |10.0.21             |DONE      |NOSIGNATURE
		[Lib]architectury-1.10.139-forge.jar              |Architectury                  |architectury                  |1.10.139            |DONE      |NOSIGNATURE
		[Service]AtlantisProxy-1.0.0.jar                  |LightfallClient               |lightfallclient               |1.0.0+6             |DONE      |NOSIGNATURE
		[Visual]ModernUI-1.16.5-2.4.9.84-universal.jar    |Modern UI                     |modernui                      |2.4.9.84            |DONE      |72:da:aa:fa:02:98:8b:71:b7:c5:ce:aa:0f:0d:cb:a3:ac:4b:97:d4:bc:fa:58:e6:98:e1:2e:ca:f4:61:a2:b0
		[Lib]cloth-config-4.11.19-forge.jar               |Cloth Config v4 API           |cloth-config                  |4.11.19             |DONE      |NOSIGNATURE
		[Fix]ProPlacer-v1.0-1.16.2.jar                    |Pro Placer                    |proplacer                     |1.0                 |DONE      |d3:cc:6f:1b:30:87:fa:d9:8f:91:15:20:27:63:95:aa:d5:cb:1b:5b:e6:36:cc:57:20:a9:b3:d4:d5:1a:5d:b8
		[M]phireworks-1.2.2.jar                           |Phireworks                    |phireworks                    |1.2.2               |DONE      |NOSIGNATURE
		[Fix]GameMenuModOption-1.16.4-1.4.jar             |Game Menu Mod Option          |gamemenumodoption             |1.4                 |DONE      |NOSIGNATURE
		[Extra]scaffoldingdropsnearby_1.16.5-1.3.jar      |Scaffolding Drops Nearby      |scaffoldingdropsnearby        |1.3                 |DONE      |NOSIGNATURE
		[M]createaddition-1.16.5-20210404a.jar            |Create Crafts & Additions     |createaddition                |1.16.5-20210404a    |DONE      |NOSIGNATURE
	Crash Report UUID: 5f0dd18c-b712-4bab-84a0-9e84a08ec30f
	Launched Version: HMCL 3.3.172
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.09, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: bbor, vanilla, mod_resources
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210305-003221
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 461.09
	OpenGlRenderer: GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
```

**Comment by mrh0** [comment]
Works for me: [Video](https://i.gyazo.com/84eb49a738773e5a6022049d6e9125f9.mp4). Try using another Forge version (I use forge:1.16.5-36.1.0)
